#!/usr/bin/env node
// Design System V2 build: src/ui (canonical) → assets/ui (published).
//
//   src/ui/tokens/*.css       → assets/ui/tokens.css   (concatenated, fixed order)
//   src/ui/components/*.css   → assets/ui/<name>.css    (copied, with a banner)
//   src/ui/layouts/*.css      → assets/ui/<name>.css
//   COMPONENT_ORDER           → assets/ui/index.css     (@import bundle)
//
// Edit src/ui, never assets/ui. `--check` fails on drift (CI gate).
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src/ui');
const OUT = path.join(ROOT, 'assets/ui');

export const TOKEN_ORDER = ['colors', 'typography', 'spacing', 'radius', 'elevation', 'motion', 'layout', 'safe-area'];
export const COMPONENT_ORDER = [
  'base', 'typography', 'buttons', 'forms', 'cards', 'badges', 'states',
  'navigation', 'dialogs', 'tables', 'utilities', 'compat'
];
/* Built and published, but not in the public index.css bundle until a web
   page adopts them: public pages should not download app-only components.
   The AppShell links them directly (and dist/app bundles them). */
export const APP_ONLY_COMPONENTS = ['feedback', 'overlays', 'toast'];

const banner = (from) => `/* GENERATED by tools/build-ui.mjs from ${from} — edit the source, not this file. */\n`;

export function buildUiFiles() {
  const files = new Map();

  const tokens = TOKEN_ORDER.map((name) => {
    const rel = `src/ui/tokens/${name}.css`;
    return `/* ---- ${rel} ---- */\n${readFileSync(path.join(ROOT, rel), 'utf8').trim()}\n`;
  }).join('\n');
  files.set('tokens.css', `${banner('src/ui/tokens/*.css')}/* Atomurus UI V2 — design tokens (canonical source: src/ui/tokens). */\n\n${tokens}`);

  const componentFiles = readdirSync(path.join(SRC, 'components')).filter((f) => f.endsWith('.css'));
  for (const file of componentFiles) {
    files.set(file, banner(`src/ui/components/${file}`) + readFileSync(path.join(SRC, 'components', file), 'utf8'));
  }
  for (const file of readdirSync(path.join(SRC, 'layouts')).filter((f) => f.endsWith('.css'))) {
    files.set(file, banner(`src/ui/layouts/${file}`) + readFileSync(path.join(SRC, 'layouts', file), 'utf8'));
  }

  const missing = COMPONENT_ORDER.filter((name) => !componentFiles.includes(`${name}.css`));
  if (missing.length) throw new Error(`COMPONENT_ORDER lists missing files: ${missing.join(', ')}`);
  const unlisted = componentFiles.map((f) => f.replace(/\.css$/, '')).filter((n) => !COMPONENT_ORDER.includes(n) && !APP_ONLY_COMPONENTS.includes(n));
  if (unlisted.length) throw new Error(`Components not in COMPONENT_ORDER: ${unlisted.join(', ')}`);

  /* /assets/* is served immutable for a year: every @import carries a
     content hash so an edited component actually reaches returning visitors. */
  const v = (name) => createHash('sha1').update(files.get(`${name}.css`)).digest('hex').slice(0, 10);
  const shellCss = readFileSync(path.join(ROOT, 'assets/layouts/shell.css'));
  const shellV = createHash('sha1').update(shellCss).digest('hex').slice(0, 10);

  files.set('index.css', `${banner('tools/build-ui.mjs COMPONENT_ORDER')}/* Atomurus UI V2 — bundle
   Load after fonts.css. Login, pricing/docs, Home, Explore, Calculators,
   Settings, Periodic Table chrome, Viewer chrome, and /app load this
   bundle. The AppShell also loads app-shell.css. */

@import url("tokens.css?v=${v('tokens')}");
${COMPONENT_ORDER.map((name) => `@import url("${name}.css?v=${v(name)}");`).join('\n')}
@import url("../layouts/shell.css?v=${shellV}");
`);
  return files;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const files = buildUiFiles();
  if (process.argv.includes('--check')) {
    const stale = [];
    for (const [name, text] of files) {
      const target = path.join(OUT, name);
      if (!existsSync(target) || readFileSync(target, 'utf8') !== text) stale.push(name);
    }
    if (stale.length) {
      console.error(`assets/ui is stale (${stale.join(', ')}) — run \`npm run build:ui\``);
      process.exit(1);
    }
    console.log('assets/ui up to date');
  } else {
    mkdirSync(OUT, { recursive: true });
    for (const [name, text] of files) writeFileSync(path.join(OUT, name), text);
    console.log(`wrote ${files.size} files to assets/ui`);
  }
}
